BOARD_NAME = "vornado-633dc"
CIRCUITPY_WIFI_SSID = "zeka_ac68u_2G"
CIRCUITPY_WIFI_PASSWORD = "43804242"
MQTT_BROKER_IP="192.168.1.2"
MQTT_BROKER_PORT=1883

# Hardware Configuration
FAN_PIN = "GP22"
POTENTIOMETER_PIN = "GP28_A2"
PWM_FREQUENCY_HZ = 1000

# Timing Configuration
WIFI_CHECK_INTERVAL_SEC = 10
POTENTIOMETER_CHECK_INTERVAL_SEC = 0.1
POTENTIOMETER_THRESHOLD_PERCENT = 1
